### ISSUE TITLE
Assertion failed, Possible upper bound limit? 

### ISSUE THREAD

**Issue by DeadZen** [vinoski/edlcbf#1]
% Recreation steps

> Bill = [ list_to_binary(integer_to_list(X)) || X <- lists:seq(1, 1000000) ].
> {ok,D} = dlcbf:new(2, 16).
> [ dlcbf:add(X, D) || X <- Bill ].
> Assertion failed: (field->f.count < ((1 << COUNTER_BITS) - 1)), function dlcbf_add, file c_src/dlcbf.c, line 153.
>                                                                                                                  Abort trap: 6

**Comment by vinoski** [comment]
Overflowing counter bits means the table is unable to accurately track collisions, which makes accurate deletion of table entries impossible. You can get this example to work if you increase the size of the table. I was able to get it to work with the following settings:

```
{ok,D} = dlcbf:new(4, 4000000).
```

**Comment by vinoski** [comment]
Since the previous comment provides a solution, closing this issue.
