### ISSUE TITLE
Module dlht_app missing in .app.src file

### ISSUE THREAD

**Issue by DeadZen** [vinoski/edlcbf#2]
{mod, { dlht_app, []}}, <- non existent, so application cannot be started.

**Comment by vinoski** [comment]
Maybe I'm missing something, but it seems to be there: https://github.com/vinoski/edlcbf/blob/master/src/dlcbf.app.src#L10

**Comment by vinoski** [comment]
Oh, I misunderstood: you're saying that the function `dlht_app:start/0` _referenced_ in the .app.src file is undefined. Will fix.

**Comment by vinoski** [comment]
Fixed in 6dc554c4.
